# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/const.xdc

# Block Designs: bd/timerproj/timerproj.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timerproj || ORIG_REF_NAME==timerproj} -quiet] -quiet

# IP: bd/timerproj/ip/timerproj_processing_system7_0_0/timerproj_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timerproj_processing_system7_0_0 || ORIG_REF_NAME==timerproj_processing_system7_0_0} -quiet] -quiet

# IP: bd/timerproj/ip/timerproj_axi_gpio_0_0/timerproj_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timerproj_axi_gpio_0_0 || ORIG_REF_NAME==timerproj_axi_gpio_0_0} -quiet] -quiet

# IP: bd/timerproj/ip/timerproj_xbar_0/timerproj_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timerproj_xbar_0 || ORIG_REF_NAME==timerproj_xbar_0} -quiet] -quiet

# IP: bd/timerproj/ip/timerproj_ps7_0_axi_periph_0/timerproj_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timerproj_ps7_0_axi_periph_0 || ORIG_REF_NAME==timerproj_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/timerproj/ip/timerproj_rst_ps7_0_50M_0/timerproj_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timerproj_rst_ps7_0_50M_0 || ORIG_REF_NAME==timerproj_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/timerproj/ip/timerproj_axi_timer_0_0/timerproj_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timerproj_axi_timer_0_0 || ORIG_REF_NAME==timerproj_axi_timer_0_0} -quiet] -quiet

# IP: bd/timerproj/ip/timerproj_auto_pc_0/timerproj_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timerproj_auto_pc_0 || ORIG_REF_NAME==timerproj_auto_pc_0} -quiet] -quiet

# XDC: bd/timerproj/timerproj_ooc.xdc
