# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Programlar/Vivado/VivadoProjects/TimerProj/TimerProj.srcs/sources_1/bd/timerproj/ip/timerproj_processing_system7_0_0/timerproj_processing_system7_0_0.xci
# IP: The module: 'timerproj_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Programlar/Vivado/VivadoProjects/TimerProj/TimerProj.srcs/sources_1/bd/timerproj/ip/timerproj_processing_system7_0_0/timerproj_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'timerproj_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Programlar/Vivado/VivadoProjects/TimerProj/TimerProj.srcs/sources_1/bd/timerproj/ip/timerproj_processing_system7_0_0/timerproj_processing_system7_0_0.xci
# IP: The module: 'timerproj_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Programlar/Vivado/VivadoProjects/TimerProj/TimerProj.srcs/sources_1/bd/timerproj/ip/timerproj_processing_system7_0_0/timerproj_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'timerproj_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
